# Generated by Django 2.1.5 on 2019-01-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('plan', models.CharField(choices=[('Full', 'Full'), ('Pro', 'Professional'), ('CRM', 'CRM')], max_length=1)),
            ],
        ),
    ]
