# Generated by Django 2.1.5 on 2019-01-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpload', models.CharField(default='Not defined', max_length=100)),
                ('lastFileUploaded', models.CharField(default='Not defined', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('admin', 'Administrator'), ('standard', 'Standard'), ('basic', 'Basic')], default='standard', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Professional'), ('advanced', 'Advanced'), ('crm', 'CRM'), ('developer', 'Developer'), ('controller', 'Controller')], default='basic', max_length=10)),
                ('token', models.CharField(default='Not defined', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Not defined', max_length=100)),
                ('department', models.CharField(default='Not defined', max_length=100)),
                ('telephone', models.CharField(default='Not defined', max_length=100)),
                ('address', models.CharField(default='Not defined', max_length=100)),
                ('postcode', models.CharField(default='Not defined', max_length=100)),
                ('city', models.CharField(default='Not defined', max_length=100)),
                ('country', models.CharField(default='Not defined', max_length=100)),
                ('vat', models.CharField(default='Not defined', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
