# Generated by Django 2.2.5 on 2019-10-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_industries(apps, schema_editor):
    IndustriesModel = apps.get_model("core", "CustomerIndustries")
    industries_list = [
                       'agriculture',
                        'banking',
                        'construction',
                        'consulting',
                        'education',
                        'government',
                        'industry_cl',
                        'manufacturing',
                        'medical',
                        'retail',
                        'services',
                        'software',
                        'transport',
                        'other',
                    ]
    for industry in industries_list:
        IndustriesModel.objects.create(
            industries_name=industry
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_avatar_avatarimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIndustries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industries_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Industries',
            },
        ),
        migrations.RunPython(add_industries),
        migrations.AlterField(
            model_name='avatarimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar/'),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industries_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomerIndustries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Industry',
            },
        ),
    ]
