# Generated by Django 2.2.5 on 2021-02-17 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20191015_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencies_name', models.CharField(default='€', max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Customer Currencies',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencies_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomerCurrencies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
    ]
