# Generated by Django 2.2.1 on 2019-09-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.TextField(blank=True, null=True)),
                ('month1', models.TextField(blank=True, null=True)),
                ('product_type1', models.TextField(blank=True, null=True)),
                ('product1', models.TextField(blank=True, null=True)),
                ('year2', models.TextField(blank=True, null=True)),
                ('month2', models.TextField(blank=True, null=True)),
                ('product_type2', models.TextField(blank=True, null=True)),
                ('product2', models.TextField(blank=True, null=True)),
                ('report_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
