# Generated by Django 2.2.5 on 2019-10-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='industory1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='industory2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
