# Generated by Django 2.2.5 on 2020-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191008_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='kam1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='kam2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
